### ISSUE TITLE
Code for this method

### ISSUE THREAD

**Issue by KunalGeed** [jason-huanghao/Core-Concept-Seeded-LDA#1]
Hey,
Is it possible to show the code on how you implemented this Core-Concept-Seeded LDA as a Term Clustering Method for core concept formation?
Regards,
Kunal

**Comment by jason-huanghao** [comment]
Hello, Kunal. We&nbsp;will&nbsp;share the code with public, but not now. I am sorry&nbsp;to tell you that I can not send you right now. We will do this (in the same github page)&nbsp;until the publication of our paper. 
Sincerely,
 Hao 
  

 ------------------&nbsp;Original&nbsp;------------------
  From: ***@***.***&gt;;
 Send time:&nbsp;Thursday, May 6, 2021 1:05 AM
 ***@***.***&gt;; 
 ***@***.***&gt;; 
 Subject: &nbsp;[jason-huanghao/Core-Concept-Seeded-LDA] Code for this method (#1)

 

 

 
Hey,
Is it possible to show the code on how you implemented this Core-Concept-Seeded LDA as a Term Clustering Method for core concept formation?
Regards,
Kunal
